repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      exclude: ^migrations/
      language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      exclude: ^migrations/
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]