data:
  object:
    source: "hourglass_tensorflow.handlers.data.HTFDataHandler"
    params:
      foo: bar
  input:
    mode: "RGB"
    source: data/images.ignore.folder
    extensions:
      - png
      - jpeg
      - jpg
  output:
    source: data/labels.ignore.csv
    source_prefixed: false
    prefix_columns:
      - set
      - image
      - scale
      - bbox_tl_x
      - bbox_tl_y
      - bbox_br_x
      - bbox_br_y
      - center_x
      - center_y
    column_set: set
    column_source: image
    joints:
      num: 16
      dynamic_fields:
        - SUFFIX
      naming_convention: joint_{JOINT_ID}_{SUFFIX}
      format:
        id_field: JOINT_ID
        SUFFIX:
          x: "X"
          y: "Y"
          visible: visible
      names:
        - "00_rAnkle"
        - "01_rKnee"
        - "02_rHip"
        - "03_lHip"
        - "04_lKnee"
        - "05_lAnkle"
        - "06_pelvis"
        - "07_thorax"
        - "08_upperNeck"
        - "09_topHead"
        - "10_rWrist"
        - "11_rElbow"
        - "12_rShoulder"
        - "13_lShoulder"
        - "14_lElbow"
        - "15_lWrist"

dataset:
  object:
    source: "hourglass_tensorflow.handlers.datasets.HTFDatasetHandler"
    params:
      foo: bar
  image_size: 256
  column_image: image
  heatmap:
    size: 64
    stacks: 3
    channels: 16
    stddev: 5.
  normalization: "ByMax"
  sets:
    split_by_column: true
    column_split: set
    value_train: TRAIN
    value_test: TEST
    value_validation: VALIDATION
    test: true
    train: true
    validation: true
    ratio_test: 0.15
    ratio_train: 0.7
    ratio_validation: 0.15
  bbox:
    activate: true
    factor: 1.5

model:
  object:
    source: "hourglass_tensorflow.handlers.model.HTFModelHandler"
    params:
      foo: bar
  build_as_model : false
  data_format: NHWC
  params:
    input_size: 256
    output_size: 64
    stages: 3
    downsamplings_per_stage: 4
    stage_filters: 256
    output_channels: 16
    name: "HourglassSample"
    intermediate_supervision: true
