mode: test
version: "1.0.0"
data:
  object:
    source: "hourglass_tensorflow.handlers.data.HTFDataHandler"
    params:
      foo: bar
  input:
    mode: "RGBD"
    #source: data/images.ignore.folder
    source: /home/quinoa/Desktop/some_shit/patient_project/SLP_RGBD_v3
    extensions:
      - png
      - jpeg
      - jpg
  output:
    #source: data/labels.ignore.csv
    source: data/htf_slp_dataset_test.ignore.json
    source_prefixed: false
    prefix_columns:
      - set
      - image
      - depth
      - scale
      - bbox_tl_x
      - bbox_tl_y
      - bbox_br_x
      - bbox_br_y
      - center_x
      - center_y
    column_set: set
    column_source: image
    joints:
      num: 14
      dynamic_fields:
        - SUFFIX
      naming_convention: joint_{JOINT_ID}_{SUFFIX}
      format:
        id_field: JOINT_ID
        SUFFIX:
          x: "X"
          y: "Y"
          visible: visible
      names:
        - "00_rAnkle"
        - "01_rKnee"
        - "02_rHip"
        - "03_lHip"
        - "04_lKnee"
        - "05_lAnkle"
        - "06_rWrist"
        - "07_rElbow"
        - "08_rShoulder"
        - "09_lShoulder"
        - "10_lElbow"
        - "11_lWrist"
        - "12_thorax"
        - "13_topHead"
  
dataset:
  object:
    source: hourglass_tensorflow.handlers.dataset.HTFDatasetHandler
    params:
      foo: bar
  image_size: 256
  data_mode: Depth
  hip_idxs:
    Lhip: 3
    Rhip: 2
  column_image: image
  heatmap:
    size: 64
    stacks: 2
    channels_1JHMs: 14
    channels_2JHMs: 12
    limbs_2J_str:
    - (0, 1)
    - (1, 2)
    - (2, 3)
    - (3, 4)
    - (4, 5)
    - (6, 7)
    - (7, 8)
    - (8, 12)
    - (9, 12)
    - (12, 13)
    - (11, 10)
    - (10, 9)
    stddev: 1.1
    stddev_factor: 1.3
    enable_visibility: true

  normalization: Idem
  augmentation: null
  sets:
    split_by_column: false
    column_split: set
    value_train: TRAIN
    value_test: TEST
    value_validation: VALIDATION
    test: true
    train: false
    validation: false
    ratio_test: 0.06
    ratio_train: 0.84
    ratio_validation: 0.1
  bbox:
    activate: true
    factor: 1.15
  task_mode: "test"

model:
  object:
    source: hourglass_tensorflow.handlers.model.HTFModelHandler
    params:
      foo: bar
  build_as_model: true
  data_format: NHWC
  batch_size: 1
  params:
    input_size: 256
    output_size: 64
    channel_number: 4
    stages: 2
    downsamplings_per_stage: 4
    stage_filters: 256
    channels_1joint: 14
    channels_2joint: 12
    name: HourglassSample
    intermediate_supervision: true
    skip_AM: NoAM
    s2f_AM: NoAM
    f2s_AM: NoAM
    use_2jointHM: true
    use_kernel_regularization: false
    freeze_attention_weights: false
    residual_nblocks: 1
  load_model: true
  model_path: data/model_t/myModel_SLP_WS_BL_1B_ATT9_Depth4C.keras #/home/quinoa/Downloads/myModel_SLP_fAB7_1j.keras #/home/quinoa/Downloads/myModel_SLP_fAB7_1j.keras #"data/model_t/myModel_SLP_fAB6_2j"
  loading_style: Frozen

test:
  object:
    source: "hourglass_tensorflow.handlers.test.HTFTestHandler"
    params:
      foo: bar
  batch_size: 80 #128


train: