mode = "train"

[dataset]
image_size = 256
column_image = "image"
normalization = "ByMax"
[[dataset.augmentation]]
source = ""

[dataset.augmentation.params]
foo = "bar"

[model]
build_as_model = false
data_format = "NHWC"

[train]
epochs = 10
epoch_size = 1000
batch_size = 128
[[train.metrics]]
source = "hourglass_tensorflow.metrics.OverallMeanDistance"

[train.metrics.params]
name = "MeanDistanceInPixel"
[[train.metrics]]
source = "hourglass_tensorflow.metrics.RatioCorrectKeypoints"

[train.metrics.params]
name = "CorrectKeypoints@10px"
threshold = 10
[[train.metrics]]
source = "hourglass_tensorflow.metrics.RatioCorrectKeypoints"

[train.metrics.params]
name = "CorrectKeypoints@5px"
threshold = 5
[[train.metrics]]
source = "hourglass_tensorflow.metrics.RatioCorrectKeypoints"

[train.metrics.params]
name = "CorrectKeypoints@20px"
threshold = 20
[[train.metrics]]
source = "hourglass_tensorflow.metrics.PercentageOfCorrectKeypoints"

[train.metrics.params]
name = "PCKh@0.5"
ratio = 0.5
[[train.metrics]]
source = "hourglass_tensorflow.metrics.PercentageOfCorrectKeypoints"

[train.metrics.params]
name = "PCKh@0.75"
ratio = 0.75
[[train.metrics]]
source = "hourglass_tensorflow.metrics.PercentageOfCorrectKeypoints"

[train.metrics.params]
name = "PCK@0.75"
ratio = 0.75
reference = [ 6, 8,]
[[train.metrics]]
source = "hourglass_tensorflow.metrics.PercentageOfCorrectKeypoints"

[train.metrics.params]
name = "PCK@0.5"
ratio = 0.5
reference = [ 6, 8,]
[[train.callbacks]]
source = "tensorflow.keras.callbacks.ModelCheckpoint"

[train.callbacks.params]
filepath = "data/model.ignore.folder/myModel.{epoch:02d}"
save_weights_only = false
save_freq = "epoch"
save_best_model = false
[[train.callbacks]]
source = "tensorflow.keras.callbacks.TensorBoard"

[train.callbacks.params]
log_dir = "logs/myModelLogs"
histogram_freq = 1
write_graph = true
write_grads = true
write_images = true
update_freq = "epoch"
[[train.callbacks]]
source = "tensorflow.keras.callbacks.CSVLogger"

[train.callbacks.params]
filename = "logs/myModelLogs.csv"

[data.object]
source = "hourglass_tensorflow.handlers.data.HTFDataHandler"

[data.input]
mode = "RGB"
source = "data/images.ignore.folder"
extensions = [ "png", "jpeg", "jpg",]

[data.output]
source = "data/labels.ignore.csv"
source_prefixed = false
prefix_columns = [ "set", "image", "scale", "bbox_tl_x", "bbox_tl_y", "bbox_br_x", "bbox_br_y", "center_x", "center_y",]
column_set = "set"
column_source = "image"

[dataset.object]
source = "hourglass_tensorflow.handlers.dataset.HTFDatasetHandler"

[dataset.heatmap]
size = 64
stacks = 2
channels = 16
stddev = 5.0

[dataset.sets]
split_by_column = true
column_split = "set"
value_train = "TRAIN"
value_test = "TEST"
value_validation = "VALIDATION"
test = true
train = true
validation = true
ratio_test = 0.15
ratio_train = 0.7
ratio_validation = 0.15

[dataset.bbox]
activate = true
factor = 1.5

[model.object]
source = "hourglass_tensorflow.handlers.model.HTFModelHandler"

[model.params]
input_size = 256
output_size = 64
stages = 2
downsamplings_per_stage = 4
stage_filters = 64
output_channels = 16
name = "HourglassSample"
intermediate_supervision = true

[train.object]
source = "hourglass_tensorflow.handlers.train.HTFTrainHandler"

[train.learning_rate]
source = "keras.optimizers.schedules.learning_rate_schedule.ExponentialDecay"

[train.loss]
source = "hourglass_tensorflow.losses.SigmoidCrossEntropyLoss"

[train.optimizer]
source = "keras.optimizers.RMSprop"

[data.object.params]
foo = "bar"

[data.output.joints]
num = 16
dynamic_fields = [ "SUFFIX",]
naming_convention = "joint_{JOINT_ID}_{SUFFIX}"
names = [ "00_rAnkle", "01_rKnee", "02_rHip", "03_lHip", "04_lKnee", "05_lAnkle", "06_pelvis", "07_thorax", "08_upperNeck", "09_topHead", "10_rWrist", "11_rElbow", "12_rShoulder", "13_lShoulder", "14_lElbow", "15_lWrist",]

[dataset.object.params]
foo = "bar"

[model.object.params]
foo = "bar"

[train.object.params]
foo = "bar"

[train.learning_rate.params]
initial_learning_rate = 0.00025
decay_steps = 1000
decay_rate = 0.96

[train.loss.params]
foo = "bar"

[train.optimizer.params]
rho = 0.9
momentum = 0.0
centered = true

[data.output.joints.format]
id_field = "JOINT_ID"

[data.output.joints.format.SUFFIX]
x = "X"
y = "Y"
visible = "visible"
