mode: train
version: "1.0.0"
data:
  object:
    source: "hourglass_tensorflow.handlers.data.HTFDataHandler"
    params:
      foo: bar
  input:
    mode: "RGB"
    #source: data/images.ignore.folder
    source: /home/ivp_lab/mpii_human_pose_v1
    extensions:
      - png
      - jpeg
      - jpg
  output:
    #source: data/labels.ignore.csv
    source: data/htf_dataset.ignore.json
    source_prefixed: false
    prefix_columns:
      - set
      - image
      - scale
      - bbox_tl_x
      - bbox_tl_y
      - bbox_br_x
      - bbox_br_y
      - center_x
      - center_y
    column_set: set
    column_source: image
    joints:
      num: 16
      dynamic_fields:
        - SUFFIX
      naming_convention: joint_{JOINT_ID}_{SUFFIX}
      format:
        id_field: JOINT_ID
        SUFFIX:
          x: "X"
          y: "Y"
          visible: visible
      names:
        - "00_rAnkle"
        - "01_rKnee"
        - "02_rHip"
        - "03_lHip"
        - "04_lKnee"
        - "05_lAnkle"
        - "06_pelvis"
        - "07_thorax"
        - "08_upperNeck"
        - "09_topHead"
        - "10_rWrist"
        - "11_rElbow"
        - "12_rShoulder"
        - "13_lShoulder"
        - "14_lElbow"
        - "15_lWrist"

dataset:
  object:
    source: "hourglass_tensorflow.handlers.dataset.HTFDatasetHandler"
    params:
      foo: bar
  image_size: 256 #256
  column_image: image
  heatmap:
    size: 64 #64
    stacks: 6
    channels: 16
    stddev: 2.0
  normalization: "Normal"
  augmentation:
    - 
      source: ""
      params:
        foo: bar
  sets:
    split_by_column: false #true
    column_split: set
    value_train: TRAIN
    value_test: TEST
    value_validation: VALIDATION
    test: true
    train: true
    validation: true
    ratio_test: 0.001
    ratio_train: 0.71
    ratio_validation: 0.25
  bbox:
    activate: true
    factor: 1.2

model:
  object:
    source: "hourglass_tensorflow.handlers.model.HTFModelHandler"
    params:
      foo: bar
  build_as_model : true
  data_format: NHWC
  params:
    input_size: 256 #256
    output_size: 64 #64
    stages: 6
    downsamplings_per_stage: 4
    stage_filters: 64 #64
    output_channels: 16
    name: "HourglassSample"
    intermediate_supervision: true

train:
  object:
    source: "hourglass_tensorflow.handlers.train.HTFTrainHandler"
    params:
      foo: bar
  epochs: 30
  epoch_size: 92
  batch_size: 70 #128
  learning_rate:
    #source: "keras.optimizers.schedules.learning_rate_schedule.ExponentialDecay"
    source: "keras.optimizers.schedules.ExponentialDecay"
    params:
      initial_learning_rate: 0.0003 #0.00025
      decay_steps: 1000
      decay_rate: 0.96
  #loss:
  #  source: "hourglass_tensorflow.losses.SigmoidCrossEntropyLoss"
  #  params:
  #    foo: bar
  loss: MeanSquaredError
  optimizer:
    source: "keras.optimizers.RMSprop"
    params:
      rho: 0.9
      momentum: 0.0
      centered: true
    #source: "keras.optimizers.Adam"
    #params:
    #  beta_1: 0.8
    #  beta_2: 0.99
    #  epsilon: 1e-08
  metrics:
    #- 
    #  source: "hourglass_tensorflow.metrics.OverallMeanDistance"
    #  params:
    #    name: "MeanDistanceInPixel"
    -
      source: "hourglass_tensorflow.metrics.RatioCorrectKeypoints"
      params:
        name: "CorrectKpts@6px"
        threshold: 6
    - 
      source: "hourglass_tensorflow.metrics.PercentageOfCorrectKeypoints"
      params:
        name: "PCK@0.2"
        ratio: 0.2
        reference:
          - 6
          - 8
  callbacks:
    #-
    #  source: "tensorflow.keras.callbacks.ModelCheckpoint"
    #  params:
        #filepath: "data/model.ignore.folder/myModel.{epoch:02d}"
        #filepath: "data/model_t/myModel.{epoch:02d}"
    #    filepath: "data/model_t/myModel"
    #    save_weights_only: false
    #    save_freq: epoch
    #    monitor: val_PCK@0.2
    #    save_best_model: true
    -
      source: "tensorflow.keras.callbacks.TensorBoard"
      params:
        log_dir: logs/myModelLogs
        histogram_freq: 1
        write_graph: true
        #write_grads: true
        write_images: true
        update_freq: epoch
    -
      source: "tensorflow.keras.callbacks.CSVLogger"
      params:
        filename: logs/myModelLogs.csv