from hourglass_tensorflow.utils.sets import split_train_test
from hourglass_tensorflow.utils._errors import BadConfigurationError
from hourglass_tensorflow.utils.writers import common_write
from hourglass_tensorflow.utils.object_logger import ObjectLogger
from hourglass_tensorflow.utils.drawing_n_plotting import draw_pose_HG,draw_pose_mplib